Repository ProVal-Tech/proval-docs, pull requests merged in 2025-07, with the labels that each got.

#218 remove-sentinelone
  docs/ninjaone/automations/remove-sentinelone.md
  static/img/docs/5b5a3254-de28-4ea1-8a7a-4f5d465ce7f1/image1.webp
  static/img/docs/5b5a3254-de28-4ea1-8a7a-4f5d465ce7f1/image2.webp
Labels: documentation, enhancement

#222 Threatlocker Agent Deployment
  docs/cwa/dataviews/windows-10-feature-update-latest-stats.md
  docs/cwa/monitors/deploy-threatlocker-agent.md
  docs/cwa/scripts/threatlocker-agent-deployment.md
  docs/cwa/scripts/threatlocker-deployment.md
  docs/cwa/scripts/user-prompt-show.md
  docs/cwa/scripts/windows-10-feature-update-install-latest.md
  docs/cwa/scripts/windows-10-feature-update-process-20h2-version.md
  docs/cwa/scripts/windows-10-feature-update-process.md
  docs/cwa/scripts/windows-10-update-stats-retrieve.md
  docs/cwa/scripts/windows-10-update.md
  docs/cwa/scripts/windows-10-upgrade-assistant.md
  docs/cwa/tables/plugin-proval-windows10-upgradestats.md
  docs/solutions/threatlocker-agent-deployment.md
  docs/solutions/windows-10-update.md
  static/img/docs/2b68cbb1-1406-4a4b-9173-e91f1b0c7f88/image1.webp
  static/img/docs/37fe5efc-3b1d-45d8-906d-0388baf6caac/image_1.webp
  static/img/docs/3f819775-4c68-4511-ad44-d97a37ca3869/image_1.webp
  static/img/docs/3f819775-4c68-4511-ad44-d97a37ca3869/image_2.webp
  static/img/docs/3f819775-4c68-4511-ad44-d97a37ca3869/image_3.webp
  static/img/docs/5a4a9091-269e-4921-a7ba-bc87c209a43c/image_1.webp
  static/img/docs/5a4a9091-269e-4921-a7ba-bc87c209a43c/image_2.webp
  static/img/docs/5a4a9091-269e-4921-a7ba-bc87c209a43c/image_3.webp
  static/img/docs/6ee04ebc-5867-4310-a8ed-1f800f031774/image1.webp
  static/img/docs/6ee04ebc-5867-4310-a8ed-1f800f031774/image2.webp
  static/img/docs/6ee04ebc-5867-4310-a8ed-1f800f031774/image3.webp
  static/img/docs/6ee04ebc-5867-4310-a8ed-1f800f031774/image4.webp
  static/img/docs/6ee04ebc-5867-4310-a8ed-1f800f031774/image5.webp
  static/img/docs/6ee04ebc-5867-4310-a8ed-1f800f031774/image6.webp
  static/img/docs/6ee04ebc-5867-4310-a8ed-1f800f031774/image7.webp
  static/img/docs/b4c2b307-41af-4ebf-8132-9f883351b09b/image_1.webp
  static/img/docs/c182b594-6dab-4c45-8aca-67807dbd23ab/image_1.webp
  static/img/docs/c182b594-6dab-4c45-8aca-67807dbd23ab/image_1_1.webp
Labels: documentation

#212 Set Time Zone
  docs/ninjaone/automations/manage-time-zone.md
  docs/ninjaone/conditions/set-time-zone-windows-servers.md
  docs/ninjaone/conditions/set-time-zone-windows-workstations.md
  docs/ninjaone/custom-fields/cpval-manage-time-zone.md
  docs/ninjaone/custom-fields/cpval-time-zone-to-set.md
  docs/solutions/manage-time-zone-ninja-one.md
  static/img/docs/080cb5cd-270d-42ee-aa69-05b88adcb35c/image1.webp
  static/img/docs/080cb5cd-270d-42ee-aa69-05b88adcb35c/image2.webp
  static/img/docs/23bc744a-aef7-40dd-bfc6-058138a4d302/image1.webp
  static/img/docs/23bc744a-aef7-40dd-bfc6-058138a4d302/image2.webp
  static/img/docs/23bc744a-aef7-40dd-bfc6-058138a4d302/image3.webp
  static/img/docs/23bc744a-aef7-40dd-bfc6-058138a4d302/image4.webp
  static/img/docs/7db8dfdf-6825-4349-94e1-f86348fdec03/image1.webp
  static/img/docs/7db8dfdf-6825-4349-94e1-f86348fdec03/image2.webp
  static/img/docs/7db8dfdf-6825-4349-94e1-f86348fdec03/image3.webp
  static/img/docs/7db8dfdf-6825-4349-94e1-f86348fdec03/image4.webp
  static/img/docs/7db8dfdf-6825-4349-94e1-f86348fdec03/image5.webp
  static/img/docs/8369d5fe-217e-4804-a59f-8aa384df6cb1/image1.webp
  static/img/docs/8369d5fe-217e-4804-a59f-8aa384df6cb1/image2.webp
  static/img/docs/8369d5fe-217e-4804-a59f-8aa384df6cb1/image3.webp
  static/img/docs/8369d5fe-217e-4804-a59f-8aa384df6cb1/image4.webp
  static/img/docs/8369d5fe-217e-4804-a59f-8aa384df6cb1/image5.webp
  static/img/docs/8369d5fe-217e-4804-a59f-8aa384df6cb1/image6.webp
  static/img/docs/9d3b6624-5e4a-48cb-babb-f355fcd1f6d9/image1.webp
  static/img/docs/9d3b6624-5e4a-48cb-babb-f355fcd1f6d9/image2.webp
  static/img/docs/9d3b6624-5e4a-48cb-babb-f355fcd1f6d9/image5.webp
  static/img/docs/a5979a59-7291-42e0-8278-d7c10aa9b557/automationsaddbutton.webp
  static/img/docs/a5979a59-7291-42e0-8278-d7c10aa9b557/customfields.webp
  static/img/docs/a5979a59-7291-42e0-8278-d7c10aa9b557/customfieldsconfiguration.webp
Labels: documentation, enhancement

#227 DattoRMM- Component - Soji Disk Cleaner
  docs/dattormm/components/epm-disk-component-soji-disk-cleaner.md
  docs/dattormm/components/soji-disk-cleaner.md
  static/attachments/itg/11821769/Soji_Disk_Cleaner.cpt
  static/attachments/itg/11821769/soji-disk-cleaner.cpt
  static/img/docs/3e424fbe-30e1-444b-a7c3-cc29793226a6/image1.webp
  static/img/docs/3e424fbe-30e1-444b-a7c3-cc29793226a6/image2.webp
  static/img/docs/3e424fbe-30e1-444b-a7c3-cc29793226a6/image3.webp
  static/img/docs/3e424fbe-30e1-444b-a7c3-cc29793226a6/image4.webp
Labels: documentation, enhancement

#234 application-latest-version-detection-winget
  docs/cwa/scripts/application-latest-version-detection-winget.md
Labels: documentation, enhancement

#236 Update unsynced-tickets.md
  docs/cwa/scripts/unsynced-tickets.md
Labels: bug, documentation

#241 Auto Reboot Management
  docs/cwa/dataviews/auto-reboot-audit.md
  docs/cwa/scripts/auto-reboot-management.md
  static/img/docs/69b28e39-89c4-498a-8c45-3d18459d39a0/image1.webp
  static/img/docs/69b28e39-89c4-498a-8c45-3d18459d39a0/image2.webp
  static/img/docs/69b28e39-89c4-498a-8c45-3d18459d39a0/image3.webp
  static/img/docs/69b28e39-89c4-498a-8c45-3d18459d39a0/image4.webp
  static/img/docs/69b28e39-89c4-498a-8c45-3d18459d39a0/image6.webp
Labels: documentation, enhancement

#244 Initialize-DellCommandUpdate
  docs/powershell/initialize-dellcommandupdate.md
Labels: documentation, enhancement

#232 Check RDP Enable status
  docs/vsax/custom-fields/cpval-rdp-enable-status.md
  docs/vsax/scripts/check-rdp-enable-status.md
  static/img/docs/0de8d08c-4627-4cea-afde-50fc36bdf1da/image1.webp
  static/img/docs/0de8d08c-4627-4cea-afde-50fc36bdf1da/image2.webp
  static/img/docs/0de8d08c-4627-4cea-afde-50fc36bdf1da/image3.webp
Labels: documentation, enhancement

#246 Modified Document
  docs/ninjaone/automations/duo-deployment-windows.md
  docs/ninjaone/automations/install-huntress-agent-windows.md
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image10.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image11.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image12.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image13.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image14.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image15.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image16.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image17.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image18.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image19.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image2.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image3.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image4.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image5.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image6.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image7.webp
  static/img/docs/3cc5e786-f5bd-4a86-85c6-89278fccaa65/image9.webp
  static/img/docs/518bff20-44d4-4206-9336-bb6922d959da/image10_1.webp
  static/img/docs/518bff20-44d4-4206-9336-bb6922d959da/image1_1.webp
  static/img/docs/518bff20-44d4-4206-9336-bb6922d959da/image2_1.webp
  static/img/docs/518bff20-44d4-4206-9336-bb6922d959da/image4_1.webp
  static/img/docs/518bff20-44d4-4206-9336-bb6922d959da/image5_1.webp
  static/img/docs/518bff20-44d4-4206-9336-bb6922d959da/image6_1.webp
  static/img/docs/518bff20-44d4-4206-9336-bb6922d959da/image7_1.webp
  static/img/docs/518bff20-44d4-4206-9336-bb6922d959da/image8.webp
  static/img/docs/518bff20-44d4-4206-9336-bb6922d959da/image9_1.webp
Labels: bug, documentation

#249 Update windows-11-installer-beta.md
  docs/cwrmm/tasks/windows-11-installer-beta.md
Labels: bug, documentation
