Repository ProVal-Tech/proval-docs, pull requests merged in 2025-05, with the labels that each got.

#112 Update automation-directory-remove-obsolete-ps1-change.md
  docs/cwa/monitors/automation-directory-remove-obsolete-ps1-change.md
Labels: bug, documentation

#127 Lockdown Browsers Autofill and Password Manager
  docs/immybot/tasks/lockdown-browsers-autofill-and-password-manager.md
  static/img/immybot-task-lockdown-browsers-autofill-and-password-manager/image_1.png
  static/img/immybot-task-lockdown-browsers-autofill-and-password-manager/image_10.png
  static/img/immybot-task-lockdown-browsers-autofill-and-password-manager/image_11.png
  static/img/immybot-task-lockdown-browsers-autofill-and-password-manager/image_2.png
  static/img/immybot-task-lockdown-browsers-autofill-and-password-manager/image_3.png
  static/img/immybot-task-lockdown-browsers-autofill-and-password-manager/image_4.png
  static/img/immybot-task-lockdown-browsers-autofill-and-password-manager/image_5.png
  static/img/immybot-task-lockdown-browsers-autofill-and-password-manager/image_6.png
  static/img/immybot-task-lockdown-browsers-autofill-and-password-manager/image_7.png
  static/img/immybot-task-lockdown-browsers-autofill-and-password-manager/image_8.png
  static/img/immybot-task-lockdown-browsers-autofill-and-password-manager/image_9.png
Labels: documentation

#136 Update install-windows11featureupdate.md
  docs/powershell/install-windows11featureupdate.md
Labels: bug, documentation, enhancement

#131 Remove - PUA documents
  docs/cwa/scripts/remove-pua.md
  docs/dattormm/components/pua-removal-tool.md
  docs/ninjaone/automations/remove-pua.md
  docs/powershell/remove-pua.md
  docs/solutions/remove-pua.md
  docs/vsa/procedures/pua-remove.md
Labels: bug, documentation

#151 Update remove-sentinelone.md
  docs/powershell/remove-sentinelone.md
Labels: bug, documentation

#150 Soji
  docs/apps/soji.md
  docs/cwrmm/tasks/soji-disk-cleanup-utility.md
  docs/dattormm/components/epm-disk-component-soji-disk-cleaner.md
  docs/ninjaone/automations/soji-disk-cleanup-utility.md
  docs/vsa/procedures/soji-disk-cleaner.md
  static/attachments/itg/11821769/Soji_Disk_Cleaner.cpt
  static/img/docs/a1d8f066-b016-4654-b855-891518d1f1da/image_22.webp
  static/img/docs/a1d8f066-b016-4654-b855-891518d1f1da/image_24.webp
  static/img/docs/ef289b50-fe18-4114-93d0-680437f7c480/image13.webp
  static/img/docs/ef289b50-fe18-4114-93d0-680437f7c480/image8.webp
Labels: documentation, enhancement

#160 Implementation Guide
  docs/immybot/software-creation.md
  docs/immybot/task-creation.md
  static/img/docs/a0b4b687-e9da-4c27-84de-383ec611c8ae/image1.webp
  static/img/docs/a0b4b687-e9da-4c27-84de-383ec611c8ae/image2.webp
  static/img/docs/a0b4b687-e9da-4c27-84de-383ec611c8ae/image3.webp
  static/img/docs/a0b4b687-e9da-4c27-84de-383ec611c8ae/image4.webp
  static/img/docs/a0b4b687-e9da-4c27-84de-383ec611c8ae/image5.webp
  static/img/docs/a0b4b687-e9da-4c27-84de-383ec611c8ae/image6.webp
  static/img/docs/a0b4b687-e9da-4c27-84de-383ec611c8ae/image7.webp
  static/img/docs/a0b4b687-e9da-4c27-84de-383ec611c8ae/image8.webp
  static/img/docs/d482ffa0-210b-4ea6-a18c-a303b9a7c14a/image1.webp
  static/img/docs/d482ffa0-210b-4ea6-a18c-a303b9a7c14a/image2.webp
  static/img/docs/d482ffa0-210b-4ea6-a18c-a303b9a7c14a/image3.webp
  static/img/docs/d482ffa0-210b-4ea6-a18c-a303b9a7c14a/image4.webp
  static/img/docs/d482ffa0-210b-4ea6-a18c-a303b9a7c14a/image5.webp
  static/img/docs/d482ffa0-210b-4ea6-a18c-a303b9a7c14a/image6.webp
  static/img/docs/d482ffa0-210b-4ea6-a18c-a303b9a7c14a/image7.webp
Labels: documentation

#157 Huntress - Reset Microsoft Defender to default
  docs/ninjaone/automations/reset-microsoft-defender-to-default.md
  static/img/docs/9d1dd608-6eec-43f4-bbed-8c1c1a5c837a/image_1.webp
  static/img/docs/9d1dd608-6eec-43f4-bbed-8c1c1a5c837a/image_2.webp
  static/img/docs/9d1dd608-6eec-43f4-bbed-8c1c1a5c837a/image_3.webp
  static/img/docs/9d1dd608-6eec-43f4-bbed-8c1c1a5c837a/image_4.webp
  static/img/docs/9d1dd608-6eec-43f4-bbed-8c1c1a5c837a/image_5.webp
Labels: documentation

#173 Set-PowerPlan
  docs/cwa/scripts/power-plan-setcreate.md
  docs/powershell/set-powerplan.md
  static/attachments/itg/14903184/PowerPlanSettingsTemplate.csv
  static/attachments/itg/15053772/PowerPlanSettingsTemplate.csv
  static/attachments/itg/15053772/ProVal_-_High_Performance.csv
  static/img/docs/05737947-e8d5-4711-a1d7-91a6db43358f/AdvancedSettings.webp
  static/img/docs/05737947-e8d5-4711-a1d7-91a6db43358f/SystemSettings.webp
Labels: documentation, enhancement

#171 Install Windows 11 Feature Update
  docs/ninjaone/automations/_template.md
  docs/ninjaone/automations/install-windows-11-feature-update-beta-reboot.md
  static/img/docs/b97b3d2c-ecc6-42ff-9236-36b14765c9b7/addcheckbox.webp
  static/img/docs/b97b3d2c-ecc6-42ff-9236-36b14765c9b7/checkboxvariable.webp
  static/img/docs/ea84e90b-2585-47e2-82b2-2f8d1519d079/image1.webp
  static/img/docs/ea84e90b-2585-47e2-82b2-2f8d1519d079/image2.webp
  static/img/docs/ea84e90b-2585-47e2-82b2-2f8d1519d079/image3.webp
  static/img/docs/ea84e90b-2585-47e2-82b2-2f8d1519d079/image4.webp
  static/img/docs/ea84e90b-2585-47e2-82b2-2f8d1519d079/image5.webp
  static/img/docs/ea84e90b-2585-47e2-82b2-2f8d1519d079/image6.webp
Labels: documentation

#169 Update install-huntress-agent-windows.md
  docs/ninjaone/automations/install-huntress-agent-windows.md
Labels: bug, documentation
