Repository ProVal-Tech/proval-docs, pull requests merged in 2025-04, with the labels that each got.

#79 RMM implementation of Remove-PUA
  docs/cwa/scripts/Remove - PUA.md
  docs/cwrmm/tasks/CW RMM - Task - Remove - PUA.md
  docs/dattormm/components/EPM - Software Management - Component - PUA Removal Tool.md
  docs/ninjaone/automations/remove-pua.md
  docs/vsa/procedures/PUA Remove.md
  static/img/Remove---PUA/image_5.png
  static/img/Remove---PUA/image_8.png
  static/img/ninjarmm-automations-remove-pua/image1.png
  static/img/ninjarmm-automations-remove-pua/image10.png
  static/img/ninjarmm-automations-remove-pua/image11.png
  static/img/ninjarmm-automations-remove-pua/image12.png
  static/img/ninjarmm-automations-remove-pua/image13.png
  static/img/ninjarmm-automations-remove-pua/image14.png
  static/img/ninjarmm-automations-remove-pua/image15.png
  static/img/ninjarmm-automations-remove-pua/image16.png
  static/img/ninjarmm-automations-remove-pua/image17.png
  static/img/ninjarmm-automations-remove-pua/image18.png
  static/img/ninjarmm-automations-remove-pua/image19.png
  static/img/ninjarmm-automations-remove-pua/image2.png
  static/img/ninjarmm-automations-remove-pua/image20.png
  static/img/ninjarmm-automations-remove-pua/image21.png
  static/img/ninjarmm-automations-remove-pua/image3.png
  static/img/ninjarmm-automations-remove-pua/image4.png
  static/img/ninjarmm-automations-remove-pua/image5.png
  static/img/ninjarmm-automations-remove-pua/image6.png
  static/img/ninjarmm-automations-remove-pua/image7.png
  static/img/ninjarmm-automations-remove-pua/image8.png
  static/img/ninjarmm-automations-remove-pua/image9.png
Labels: documentation

#81 install-windows-11-feature-update-beta-reboot
  docs/cwa/scripts/install-windows-11-feature-update-beta-reboot.md
  docs/powershell/Install-Windows11FeatureUpdate.md
  docs/powershell/Remove-PUA.md
  docs/powershell/Remove-UserProfile.md
  static/img/install-windows-11-feature-update-beta-reboot/image1.png
Labels: documentation, enhancement

#93 CW RMM Templates
  docs/cwrmm/custom-fields/_template.md
  docs/cwrmm/groups/_template.md
  docs/cwrmm/monitors/_template.md
  docs/cwrmm/tasks/_template.md
  static/img/cw-rmm-custom-fields-common-screenshots/step1.png
  static/img/cw-rmm-custom-fields-common-screenshots/step2.png
  static/img/cw-rmm-groups-common-screenshots/step1.png
  static/img/cw-rmm-groups-common-screenshots/step2.png
  static/img/cw-rmm-groups-common-screenshots/step3.png
  static/img/cw-rmm-groups-common-screenshots/step4.png
  static/img/cw-rmm-groups-common-screenshots/step5.png
  static/img/cw-rmm-monitors-common-screenshots/step1.png
  static/img/cw-rmm-monitors-common-screenshots/step2.png
  static/img/cw-rmm-monitors-common-screenshots/step3.png
  static/img/cw-rmm-monitors-common-screenshots/step4.png
  static/img/cw-rmm-monitors-common-screenshots/step5.png
  static/img/cw-rmm-tasks-common-screenshots/addnewscriptparameter.png
  static/img/cw-rmm-tasks-common-screenshots/addparameter.png
  static/img/cw-rmm-tasks-common-screenshots/addrow.png
  static/img/cw-rmm-tasks-common-screenshots/blankfunction.png
  static/img/cw-rmm-tasks-common-screenshots/step1.png
  static/img/cw-rmm-tasks-common-screenshots/step2.png
  static/img/cw-rmm-tasks-common-screenshots/step3.png
Labels: documentation

#94 Update Install-Windows11FeatureUpdate.md
  docs/powershell/install-windows11featureupdate.md
Labels: documentation, enhancement

#105 Update invoke-toastnotification.md
  docs/powershell/invoke-toastnotification.md
Labels: documentation, enhancement

#91 Update FileZilla
  docs/cwa/monitors/update-filezilla.md
  docs/cwa/scripts/filezilla-fetch-latest-version.md
  docs/cwa/scripts/filezilla-install-update.md
  docs/solutions/update-filezilla.md
  static/img/cwa-script-filezilla-fetch-latest-version/image1.png
  static/img/cwa-script-filezilla-install-update/image1.png
  static/img/cwa-script-filezilla-install-update/image2.png
Labels: documentation, enhancement

#109 Update duo-deployment-ninja-one.md
  docs/solutions/duo-deployment-ninja-one.md
Labels: bug, documentation

#110 Update Toast-Notification
  docs/cwa/scripts/toast-notification-template.md
  docs/cwa/scripts/toast-notification.md
  docs/cwrmm/tasks/toast-notification.md
  static/img/cw-rmm-task-toast-notification/Parameter18.png
  static/img/cw-rmm-task-toast-notification/ParameterBlock.png
Labels: documentation, enhancement

#111 Intune Enrollment and Windows Repair
  docs/cwa/scripts/windows-update-repair.md
  docs/ninjaone/automations/intune-enrollment-for-entra-joined-devices.md
  docs/ninjaone/automations/repair-windows-update.md
  static/img/Intune-Enrollment-For-Entra-Devices/image1.png
  static/img/Intune-Enrollment-For-Entra-Devices/image2.png
  static/img/Intune-Enrollment-For-Entra-Devices/image3.png
  static/img/Intune-Enrollment-For-Entra-Devices/image4.png
  static/img/Intune-Enrollment-For-Entra-Devices/image5.png
  static/img/NinjaOne-Repair-Windows-Update/Image10.png
  static/img/NinjaOne-Repair-Windows-Update/image1.png
  static/img/NinjaOne-Repair-Windows-Update/image2.png
  static/img/NinjaOne-Repair-Windows-Update/image3.png
  static/img/NinjaOne-Repair-Windows-Update/image4.png
  static/img/NinjaOne-Repair-Windows-Update/image5.png
  static/img/NinjaOne-Repair-Windows-Update/image6.png
  static/img/NinjaOne-Repair-Windows-Update/image7.png
  static/img/NinjaOne-Repair-Windows-Update/image8.png
  static/img/NinjaOne-Repair-Windows-Update/image9.png
Labels: documentation

#114 Install Windows 11 Feature Update
  docs/cwa/scripts/windows-11-installer-beta.md
  docs/cwrmm/tasks/_template.md
  docs/cwrmm/tasks/install-windows-11-feature-update.md
  docs/solutions/windows-10-to-11-upgrade.md
  static/img/Windows-11-Installer-(Beta)/image_1.png
  static/img/Windows-11-Installer-(Beta)/image_2.png
  static/img/cw-rmm-task-install-windows-11-feature-update/image1.png
  static/img/cw-rmm-task-install-windows-11-feature-update/image2.png
  static/img/cw-rmm-task-install-windows-11-feature-update/image3.png
  static/img/cw-rmm-task-install-windows-11-feature-update/image4.png
  static/img/cw-rmm-task-install-windows-11-feature-update/image5.png
  static/img/cw-rmm-task-install-windows-11-feature-update/image6.png
  static/img/cw-rmm-task-install-windows-11-feature-update/image7.png
  static/img/cw-rmm-tasks-common-screenshots/addedpowershellfunction.png
  static/img/cw-rmm-tasks-common-screenshots/addpowershellfunction.png
  static/img/cw-rmm-tasks-common-screenshots/addrow.png
  static/img/cw-rmm-tasks-common-screenshots/addscriptlogfunction.png
  static/img/cw-rmm-tasks-common-screenshots/blankpowershellfunction.png
  static/img/cw-rmm-tasks-common-screenshots/blankscriptlogfunction.png
  static/img/cw-rmm-tasks-common-screenshots/outputscriptlogfunction.png
  static/img/cw-rmm-tasks-common-screenshots/savebutton.png
Labels: documentation

#117 Deploy-AvailableCumulativeUpdate
  docs/powershell/deploy-availablecumulativeupdate.md
Labels: documentation, enhancement
